### ISSUE TITLE
Add a `--chunkSize` param when using `--asTask`

### ISSUE THREAD

**Issue by khalwat** [TopShelfCraft/Craft3-Walk#1]
Add the ability to group the tasks into chunks for processing, so a separate queue job isn't created for every step, but rather every chunk.

This would allow for running a queue job that processes, say, 10 elements at once or such, and could reduce some unnecessary overhead.

**Comment by jalendport** [comment]
This issue has been moved over to our original Walk repo (per #3) - https://github.com/TopShelfCraft/Walk/issues/3
