### ISSUE TITLE
Craft 3 support?

### ISSUE THREAD

**Issue by jon-heller** [TopShelfCraft/Craft3-Walk#2]
I know this plugin is listed under Craft 3 plugins (and has it in the repo title), but we ran into some issues i.e. calling `Craft::$app->getConfig()->maxPowerCaptain();` instead of `\craft\Helpers\App::maxPowerCaptain();`. 

We also got an error using the example

`./craft walk entries --section=blog --limit=null elements.saveElement`

`Calling [elements.saveElement] on each Entry.Exception 'TypeError' with message 'Argument 3 passed to craft\services\Elements::saveElement() must be of the type boolean, null given'`

Thank you!

**Comment by michaelrog** [comment]
Thanks Jon! Feel free to PR fixes for this to the `dev` branch if you can, or I'll take a look as soon as possible.

**Comment by jalendport** [comment]
This issue has been moved over to our original Walk repo (per #3) - https://github.com/TopShelfCraft/Walk/issues/2
